name: Build and Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t 192.168.1.10:5000/mem-zero:dev .

      - name: Push image
        run: docker push 192.168.1.10:5000/mem-zero:dev
